module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/LMlfzAc3iDj2pdQMmxwoXu',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/XkyWNN4Q/tourl-1765878318885.jpg',
    NEWSLETTER_JID: '120363406176407309@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ＮＩＫＫＡ ＭＩＮＩ Ｖ1',
    OWNER_NAME: 'NIKILA KESHARA',
    OWNER_NUMBER: '94761527735,94765849446',
    BOT_VERSION: '5.0.0',
    BOT_FOOTER: '> ＮＩＫＫＡ ＭＩＮＩ Ｖ1',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6DWa2FnSzANppXMb1u',
};
